services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend